// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/shipping/service.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_shipping_service_proto protoreflect.FileDescriptor

const file_api_shipping_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/shipping/service.proto\x12\x17smartshippingaggregator\x1a\x1bapi/shipping/shipping.proto2u\n" +
	"\x0fShippingService\x12b\n" +
	"\tGetQuotes\x12).smartshippingaggregator.GetQuotesRequest\x1a*.smartshippingaggregator.GetQuotesResponseB=Z;github.com/paciorek-lukasz/smart-shipping-aggregator/api/shippingb\x06proto3"

var file_api_shipping_service_proto_goTypes = []any{
	(*GetQuotesRequest)(nil),  // 0: smartshippingaggregator.GetQuotesRequest
	(*GetQuotesResponse)(nil), // 1: smartshippingaggregator.GetQuotesResponse
}
var file_api_shipping_service_proto_depIdxs = []int32{
	0, // 0: smartshippingaggregator.ShippingService.GetQuotes:input_type -> smartshippingaggregator.GetQuotesRequest
	1, // 1: smartshippingaggregator.ShippingService.GetQuotes:output_type -> smartshippingaggregator.GetQuotesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_shipping_service_proto_init() }
func file_api_shipping_service_proto_init() {
	if File_api_shipping_service_proto != nil {
		return
	}
	file_api_shipping_shipping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shipping_service_proto_rawDesc), len(file_api_shipping_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shipping_service_proto_goTypes,
		DependencyIndexes: file_api_shipping_service_proto_depIdxs,
	}.Build()
	File_api_shipping_service_proto = out.File
	file_api_shipping_service_proto_goTypes = nil
	file_api_shipping_service_proto_depIdxs = nil
}
