// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/shipping/shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationType int32

const (
	LocationType_TYPE_LOCKER        LocationType = 0
	LocationType_TYPE_SERVICE_POINT LocationType = 1
	LocationType_TYPE_UNKNOWN       LocationType = 2
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "TYPE_LOCKER",
		1: "TYPE_SERVICE_POINT",
		2: "TYPE_UNKNOWN",
	}
	LocationType_value = map[string]int32{
		"TYPE_LOCKER":        0,
		"TYPE_SERVICE_POINT": 1,
		"TYPE_UNKNOWN":       2,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_shipping_shipping_proto_enumTypes[0].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_api_shipping_shipping_proto_enumTypes[0]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

type GetQuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Party                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     *Party                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Package       *Package               `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuotesRequest) Reset() {
	*x = GetQuotesRequest{}
	mi := &file_api_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesRequest) ProtoMessage() {}

func (x *GetQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesRequest.ProtoReflect.Descriptor instead.
func (*GetQuotesRequest) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuotesRequest) GetSender() *Party {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GetQuotesRequest) GetRecipient() *Party {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *GetQuotesRequest) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

type GetQuotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*Option              `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuotesResponse) Reset() {
	*x = GetQuotesResponse{}
	mi := &file_api_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesResponse) ProtoMessage() {}

func (x *GetQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesResponse.ProtoReflect.Descriptor instead.
func (*GetQuotesResponse) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuotesResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type Party struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_api_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *Party) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Party) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Party) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Party) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address information such as street, building number, apartament number
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PostalCode    string `protobuf:"bytes,2,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	City          string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country       string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Longitude     string `protobuf:"bytes,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      string `protobuf:"bytes,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_shipping_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *Address) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

type Package struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Price is provided in cents
	TotalPrice    int32       `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Currency      string      `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Dimensions    *Dimensions `protobuf:"bytes,4,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_api_shipping_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *Package) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Package) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Package) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Package) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type Item struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ItemId int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sku    string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Price is provided in cents
	Price         int32 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_shipping_shipping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Dimensions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LengthCm       int32                  `protobuf:"varint,1,opt,name=length_cm,json=lengthCm,proto3" json:"length_cm,omitempty"`
	WidthCm        int32                  `protobuf:"varint,2,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	HeightCm       int32                  `protobuf:"varint,3,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	TotalWeightG   int32                  `protobuf:"varint,4,opt,name=total_weight_g,json=totalWeightG,proto3" json:"total_weight_g,omitempty"`
	TotalVolumeCm3 int32                  `protobuf:"varint,5,opt,name=total_volume_cm3,json=totalVolumeCm3,proto3" json:"total_volume_cm3,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_api_shipping_shipping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{6}
}

func (x *Dimensions) GetLengthCm() int32 {
	if x != nil {
		return x.LengthCm
	}
	return 0
}

func (x *Dimensions) GetWidthCm() int32 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *Dimensions) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *Dimensions) GetTotalWeightG() int32 {
	if x != nil {
		return x.TotalWeightG
	}
	return 0
}

func (x *Dimensions) GetTotalVolumeCm3() int32 {
	if x != nil {
		return x.TotalVolumeCm3
	}
	return 0
}

type Option struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OptionId       int32                  `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	CarrierProduct string                 `protobuf:"bytes,2,opt,name=carrier_product,json=carrierProduct,proto3" json:"carrier_product,omitempty"`
	// Price is provided in cents
	Price             int32               `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency          string              `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	DeliveryTimeSlots []*DeliveryTimeSlot `protobuf:"bytes,5,rep,name=delivery_time_slots,json=deliveryTimeSlots,proto3" json:"delivery_time_slots,omitempty"`
	PickupPoints      []*PickupPoint      `protobuf:"bytes,6,rep,name=pickup_points,json=pickupPoints,proto3" json:"pickup_points,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_api_shipping_shipping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{7}
}

func (x *Option) GetOptionId() int32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *Option) GetCarrierProduct() string {
	if x != nil {
		return x.CarrierProduct
	}
	return ""
}

func (x *Option) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Option) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Option) GetDeliveryTimeSlots() []*DeliveryTimeSlot {
	if x != nil {
		return x.DeliveryTimeSlots
	}
	return nil
}

func (x *Option) GetPickupPoints() []*PickupPoint {
	if x != nil {
		return x.PickupPoints
	}
	return nil
}

type DeliveryTimeSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time slots are provided in RFC3339
	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// Time slots are provided in RFC3339
	End           string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	TimeZone      string `protobuf:"bytes,3,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryTimeSlot) Reset() {
	*x = DeliveryTimeSlot{}
	mi := &file_api_shipping_shipping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryTimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryTimeSlot) ProtoMessage() {}

func (x *DeliveryTimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryTimeSlot.ProtoReflect.Descriptor instead.
func (*DeliveryTimeSlot) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{8}
}

func (x *DeliveryTimeSlot) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *DeliveryTimeSlot) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *DeliveryTimeSlot) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type PickupPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickupPointId string                 `protobuf:"bytes,1,opt,name=pickup_point_id,json=pickupPointId,proto3" json:"pickup_point_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	LocationType  LocationType           `protobuf:"varint,5,opt,name=location_type,json=locationType,proto3,enum=smartshippingaggregator.LocationType" json:"location_type,omitempty"`
	OpeningHours  []*OpeningHour         `protobuf:"bytes,6,rep,name=opening_hours,json=openingHours,proto3" json:"opening_hours,omitempty"`
	IsOperational bool                   `protobuf:"varint,7,opt,name=is_operational,json=isOperational,proto3" json:"is_operational,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupPoint) Reset() {
	*x = PickupPoint{}
	mi := &file_api_shipping_shipping_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupPoint) ProtoMessage() {}

func (x *PickupPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupPoint.ProtoReflect.Descriptor instead.
func (*PickupPoint) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{9}
}

func (x *PickupPoint) GetPickupPointId() string {
	if x != nil {
		return x.PickupPointId
	}
	return ""
}

func (x *PickupPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PickupPoint) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PickupPoint) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PickupPoint) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_TYPE_LOCKER
}

func (x *PickupPoint) GetOpeningHours() []*OpeningHour {
	if x != nil {
		return x.OpeningHours
	}
	return nil
}

func (x *PickupPoint) GetIsOperational() bool {
	if x != nil {
		return x.IsOperational
	}
	return false
}

type OpeningHour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayOfWeek     string                 `protobuf:"bytes,1,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	Opens         string                 `protobuf:"bytes,2,opt,name=opens,proto3" json:"opens,omitempty"`
	Closes        string                 `protobuf:"bytes,3,opt,name=closes,proto3" json:"closes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningHour) Reset() {
	*x = OpeningHour{}
	mi := &file_api_shipping_shipping_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningHour) ProtoMessage() {}

func (x *OpeningHour) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipping_shipping_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningHour.ProtoReflect.Descriptor instead.
func (*OpeningHour) Descriptor() ([]byte, []int) {
	return file_api_shipping_shipping_proto_rawDescGZIP(), []int{10}
}

func (x *OpeningHour) GetDayOfWeek() string {
	if x != nil {
		return x.DayOfWeek
	}
	return ""
}

func (x *OpeningHour) GetOpens() string {
	if x != nil {
		return x.Opens
	}
	return ""
}

func (x *OpeningHour) GetCloses() string {
	if x != nil {
		return x.Closes
	}
	return ""
}

var File_api_shipping_shipping_proto protoreflect.FileDescriptor

const file_api_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/shipping/shipping.proto\x12\x17smartshippingaggregator\"\xc4\x01\n" +
	"\x10GetQuotesRequest\x126\n" +
	"\x06sender\x18\x01 \x01(\v2\x1e.smartshippingaggregator.PartyR\x06sender\x12<\n" +
	"\trecipient\x18\x02 \x01(\v2\x1e.smartshippingaggregator.PartyR\trecipient\x12:\n" +
	"\apackage\x18\x03 \x01(\v2 .smartshippingaggregator.PackageR\apackage\"N\n" +
	"\x11GetQuotesResponse\x129\n" +
	"\aoptions\x18\x01 \x03(\v2\x1f.smartshippingaggregator.OptionR\aoptions\"\x83\x01\n" +
	"\x05Party\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\aaddress\x18\x02 \x01(\v2 .smartshippingaggregator.AddressR\aaddress\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\xac\x01\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vpostal_code\x18\x02 \x01(\tR\n" +
	"postalCode\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\tR\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\tR\blatitude\"\xc0\x01\n" +
	"\aPackage\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.smartshippingaggregator.ItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x05R\n" +
	"totalPrice\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12C\n" +
	"\n" +
	"dimensions\x18\x04 \x01(\v2#.smartshippingaggregator.DimensionsR\n" +
	"dimensions\"w\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"\xb1\x01\n" +
	"\n" +
	"Dimensions\x12\x1b\n" +
	"\tlength_cm\x18\x01 \x01(\x05R\blengthCm\x12\x19\n" +
	"\bwidth_cm\x18\x02 \x01(\x05R\awidthCm\x12\x1b\n" +
	"\theight_cm\x18\x03 \x01(\x05R\bheightCm\x12$\n" +
	"\x0etotal_weight_g\x18\x04 \x01(\x05R\ftotalWeightG\x12(\n" +
	"\x10total_volume_cm3\x18\x05 \x01(\x05R\x0etotalVolumeCm3\"\xa6\x02\n" +
	"\x06Option\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\x05R\boptionId\x12'\n" +
	"\x0fcarrier_product\x18\x02 \x01(\tR\x0ecarrierProduct\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12Y\n" +
	"\x13delivery_time_slots\x18\x05 \x03(\v2).smartshippingaggregator.DeliveryTimeSlotR\x11deliveryTimeSlots\x12I\n" +
	"\rpickup_points\x18\x06 \x03(\v2$.smartshippingaggregator.PickupPointR\fpickupPoints\"W\n" +
	"\x10DeliveryTimeSlot\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x1b\n" +
	"\ttime_zone\x18\x03 \x01(\tR\btimeZone\"\xd9\x02\n" +
	"\vPickupPoint\x12&\n" +
	"\x0fpickup_point_id\x18\x01 \x01(\tR\rpickupPointId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\aaddress\x18\x03 \x01(\v2 .smartshippingaggregator.AddressR\aaddress\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12J\n" +
	"\rlocation_type\x18\x05 \x01(\x0e2%.smartshippingaggregator.LocationTypeR\flocationType\x12I\n" +
	"\ropening_hours\x18\x06 \x03(\v2$.smartshippingaggregator.OpeningHourR\fopeningHours\x12%\n" +
	"\x0eis_operational\x18\a \x01(\bR\risOperational\"[\n" +
	"\vOpeningHour\x12\x1e\n" +
	"\vday_of_week\x18\x01 \x01(\tR\tdayOfWeek\x12\x14\n" +
	"\x05opens\x18\x02 \x01(\tR\x05opens\x12\x16\n" +
	"\x06closes\x18\x03 \x01(\tR\x06closes*I\n" +
	"\fLocationType\x12\x0f\n" +
	"\vTYPE_LOCKER\x10\x00\x12\x16\n" +
	"\x12TYPE_SERVICE_POINT\x10\x01\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x02B=Z;github.com/dzwiedz90/smart-shipping-aggregator/api/shippingb\x06proto3"

var (
	file_api_shipping_shipping_proto_rawDescOnce sync.Once
	file_api_shipping_shipping_proto_rawDescData []byte
)

func file_api_shipping_shipping_proto_rawDescGZIP() []byte {
	file_api_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_api_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shipping_shipping_proto_rawDesc), len(file_api_shipping_shipping_proto_rawDesc)))
	})
	return file_api_shipping_shipping_proto_rawDescData
}

var file_api_shipping_shipping_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_shipping_shipping_proto_goTypes = []any{
	(LocationType)(0),         // 0: smartshippingaggregator.LocationType
	(*GetQuotesRequest)(nil),  // 1: smartshippingaggregator.GetQuotesRequest
	(*GetQuotesResponse)(nil), // 2: smartshippingaggregator.GetQuotesResponse
	(*Party)(nil),             // 3: smartshippingaggregator.Party
	(*Address)(nil),           // 4: smartshippingaggregator.Address
	(*Package)(nil),           // 5: smartshippingaggregator.Package
	(*Item)(nil),              // 6: smartshippingaggregator.Item
	(*Dimensions)(nil),        // 7: smartshippingaggregator.Dimensions
	(*Option)(nil),            // 8: smartshippingaggregator.Option
	(*DeliveryTimeSlot)(nil),  // 9: smartshippingaggregator.DeliveryTimeSlot
	(*PickupPoint)(nil),       // 10: smartshippingaggregator.PickupPoint
	(*OpeningHour)(nil),       // 11: smartshippingaggregator.OpeningHour
}
var file_api_shipping_shipping_proto_depIdxs = []int32{
	3,  // 0: smartshippingaggregator.GetQuotesRequest.sender:type_name -> smartshippingaggregator.Party
	3,  // 1: smartshippingaggregator.GetQuotesRequest.recipient:type_name -> smartshippingaggregator.Party
	5,  // 2: smartshippingaggregator.GetQuotesRequest.package:type_name -> smartshippingaggregator.Package
	8,  // 3: smartshippingaggregator.GetQuotesResponse.options:type_name -> smartshippingaggregator.Option
	4,  // 4: smartshippingaggregator.Party.address:type_name -> smartshippingaggregator.Address
	6,  // 5: smartshippingaggregator.Package.items:type_name -> smartshippingaggregator.Item
	7,  // 6: smartshippingaggregator.Package.dimensions:type_name -> smartshippingaggregator.Dimensions
	9,  // 7: smartshippingaggregator.Option.delivery_time_slots:type_name -> smartshippingaggregator.DeliveryTimeSlot
	10, // 8: smartshippingaggregator.Option.pickup_points:type_name -> smartshippingaggregator.PickupPoint
	4,  // 9: smartshippingaggregator.PickupPoint.address:type_name -> smartshippingaggregator.Address
	0,  // 10: smartshippingaggregator.PickupPoint.location_type:type_name -> smartshippingaggregator.LocationType
	11, // 11: smartshippingaggregator.PickupPoint.opening_hours:type_name -> smartshippingaggregator.OpeningHour
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_shipping_shipping_proto_init() }
func file_api_shipping_shipping_proto_init() {
	if File_api_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shipping_shipping_proto_rawDesc), len(file_api_shipping_shipping_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_api_shipping_shipping_proto_depIdxs,
		EnumInfos:         file_api_shipping_shipping_proto_enumTypes,
		MessageInfos:      file_api_shipping_shipping_proto_msgTypes,
	}.Build()
	File_api_shipping_shipping_proto = out.File
	file_api_shipping_shipping_proto_goTypes = nil
	file_api_shipping_shipping_proto_depIdxs = nil
}
