// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	client "github.com/dzwiedz90/smart-shipping-aggregator/internal/provider/dhl/client"
	gomock "github.com/golang/mock/gomock"
)

// MockapiClient is a mock of apiClient interface.
type MockapiClient struct {
	ctrl     *gomock.Controller
	recorder *MockapiClientMockRecorder
}

// MockapiClientMockRecorder is the mock recorder for MockapiClient.
type MockapiClientMockRecorder struct {
	mock *MockapiClient
}

// NewMockapiClient creates a new mock instance.
func NewMockapiClient(ctrl *gomock.Controller) *MockapiClient {
	mock := &MockapiClient{ctrl: ctrl}
	mock.recorder = &MockapiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockapiClient) EXPECT() *MockapiClientMockRecorder {
	return m.recorder
}

// GetQuotesHome mocks base method.
func (m *MockapiClient) GetQuotesHome(ctx context.Context, req *client.DhlHomeApiRequest) (*client.DhlHomeApiResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotesHome", ctx, req)
	ret0, _ := ret[0].(*client.DhlHomeApiResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotesHome indicates an expected call of GetQuotesHome.
func (mr *MockapiClientMockRecorder) GetQuotesHome(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotesHome", reflect.TypeOf((*MockapiClient)(nil).GetQuotesHome), ctx, req)
}

// GetQuotesPickup mocks base method.
func (m *MockapiClient) GetQuotesPickup(ctx context.Context, req *client.DhlPickupApiRequest) (*client.DhlPickupApiResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotesPickup", ctx, req)
	ret0, _ := ret[0].(*client.DhlPickupApiResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotesPickup indicates an expected call of GetQuotesPickup.
func (mr *MockapiClientMockRecorder) GetQuotesPickup(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotesPickup", reflect.TypeOf((*MockapiClient)(nil).GetQuotesPickup), ctx, req)
}
